# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0002_mailcontact_terms_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcontact',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
