# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import mailinglist.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0003_auto_20161111_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcontact',
            name='terms_accepted',
            field=models.BooleanField(default=False, validators=[mailinglist.validators.validate_terms_accepted]),
        ),
    ]
