# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0004_auto_20161112_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcontact',
            name='delete_key',
            field=models.CharField(blank=True, default=None, max_length=32),
        ),
    ]
