# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0009_auto_20161127_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcontact',
            name='delete_key',
            field=models.CharField(default=111, max_length=32),
        ),
    ]
