# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0014_mailcontact_delete_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcontact',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
