# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='fact',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
